ExpensePortal/Models/DocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using System.Web.Routing;

using ExpensePortal.ExpensesServiceReference;
using ExpensePortal.DocumentServiceReference;
using ExpensePortal.PayrollOneServiceReference;
using ExpensePortal.Helpers;

namespace ExpensePortal.Models
{
    public class DocumentViewModel
    {
        DocumentServiceClient _documentService = new DocumentServiceClient();
        PayrollOneServiceClient _payrollOneService = new PayrollOneServiceClient();
        private readonly List<DocumentDescripton> _documentDescripton = new List<DocumentDescripton>();
     
        public string CategoryType { get; set; }
    

        public List<DocumentDescripton> GetDocumentDescripton
        {
            get
            {
                var result = _documentService.GetDocumentDescriptions(DocumentHelper.ProductType, DocumentHelper.EmployeePayrollNumber, DocumentHelper.CategoryList);
                var newResult = result.Where(d => d.Category == CategoryType);
                _documentDescripton.AddRange(newResult.Reverse());
                return _documentDescripton;
            }
        }

        public int GetWeekOfYear(DateTime datetime)
        {
            int getWeek = DateTimeHelper.WeekOfYear(datetime);
            return getWeek;
            
           
        }
        
    }
}

ExpensePortal/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using ExpensePortal.DocumentServiceReference;
using ExpensePortal.ExpensesServiceReference;
using ExpensePortal.Helpers;
using ExpensePortal.Models;
using System.Data;
using System.IO;

namespace ExpensePortal.Controllers
{
    public class DocumentController : Controller
    {

        private AuthorizationServiceClient _authorizationService = new AuthorizationServiceClient();
        private DocumentServiceClient _documentService = new DocumentServiceClient();
        private DocumentHelper _documentHelper = new DocumentHelper();
        string fileName;

        public ActionResult Index()
        {
            if (!AuthenticationHelper.IsActiveSession(_authorizationService))
            {
                return RedirectToAction("Login", "Account");
            }
            return RedirectToAction("Overview");
        }

        public ActionResult Documents(string CategoryType)
        {
            if (!AuthenticationHelper.IsActiveSession(_authorizationService))
            {
                // If not logged in this will redirect to Login
                return RedirectToAction("Login", "Account");
            }
            var model = new DocumentViewModel();
            _documentHelper.SetProductNameAndPayrollNumber();
            model.CategoryType = CategoryType;
            return View(model);
        }
        public ActionResult DocumentView(string Name)
        {
            if (!AuthenticationHelper.IsActiveSession(_authorizationService)) return RedirectToAction("Login", "Account");
            string userName = AuthenticationHelper.GetCookieValue(AuthenticationHelper.LoginCookieName, "username");
            var model = new DocumentViewModel();
            var documentDetails = _documentService.GetDocumentDescriptions(DocumentHelper.ProductType, DocumentHelper.EmployeePayrollNumber, DocumentHelper.CategoryList);
            fileName = documentDetails.Where(x => x.FileName == Name).FirstOrDefault().Descriptor;
            FileStream fileStream = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            Response.AppendHeader("Content-Disposition", "inline; filename=" + Name);
            return File(fileStream, "application/pdf");
        }


    }
}

ExpensePortal/Views/Document/Documents.cshtml
@model ExpensePortal.Models.DocumentViewModel

@{
    ViewBag.Title = "Documents";
}
<div class="row">
    @*<h1>@Html.DisplayFor(m => m.CategoryType)</h1>*@
    <h1>Payslips</h1>
    <div style="display:none;">
        @using (Html.BeginForm("Documents", "Document", FormMethod.Post))
        {

        }
    </div>

    @{
        var GetDocumentDescriptons = Model.GetDocumentDescripton;
        int rowID = 0;
        if (GetDocumentDescriptons.Count <= 0)
        {

            <div id="divDocument" class="row">
                <div class="sixcol">

                    <div class="field">

                        <div style="padding: 10px;  text-align: center;"> No Payslip Available</div>
                    </div>

                </div>

            </div>

        }
        else
        {

            if (GetDocumentDescriptons.Any())
            {


                <div id="divDocument" class="row">
                    <div class="sixcol">

                        <div class="field">

                            <table id="tblDocument" class="tableBorderSet" align="center"  style="border: 1px solid #9b26b6;  text-align: center;">
                                <thead>
                                    <tr>
                                        <th class="thcss">No</th>
                                        <th class="thcss">Year</th>
                                        <th class="thcss">Week</th>
                                        <th class="thcss">Week Ending</th>
                                        <th class="thcss"> </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var GetDocumentDescripton in GetDocumentDescriptons)
                                    {
                                        var Name = GetDocumentDescripton.FileName;
                                        //var Year = GetDocumentDescripton.UpdatedUtc.Year;
                                        var ProcessDate = Name.Split('_');
                                        var ProcessDateNew = Convert.ToDateTime(ProcessDate[7] + "/" + ProcessDate[6] + "/" + ProcessDate[5]);
                                        var YearLastTwoDigit = ProcessDate[5].Substring(2,2);
                                        var WeekOfYear = Model.GetWeekOfYear(ProcessDateNew);
                                        var DayOfWeek = GetDocumentDescripton.UpdatedUtc.DayOfWeek;
                                       // var Year2 = GetDocumentDescripton.UpdatedUtc.Year.ToString().Substring(2, 2);
                                        //var Month = GetDocumentDescripton.UpdatedUtc.Month;
                                        var YearNew = "Year";
                                        if (Convert.ToInt32(ProcessDate[6])<04)
                                        {
                                                YearNew = (Convert.ToInt32(ProcessDate[5]) - 1).ToString() + '-' + YearLastTwoDigit;
                                        }
                                        else
                                        {
                                            YearNew = ProcessDate[5].ToString() + '-' + (Convert.ToInt32(YearLastTwoDigit) + 1).ToString();
                                        }
                                        <tr>
                                            <td class="tdcss">@(rowID + 1)</td>
                                            @*<td class="tdcss">@(Year -1)-@Year2</td>*@
                                            @*<td class="tdcss">@(Month < 4) ?@(Year -1)-@Year2:@Year-@(Convert.ToInt32(Year2)+1) </td>*@
                                            <td class="tdcss">@YearNew</td>
                                            <td class="tdcss">@WeekOfYear </td>
                                            <td class="tdcss">@DayOfWeek</td>
                                            <td class="tdcss">@Html.ActionLink("View " + Model.CategoryType, "DocumentView", new {Name = @Name }, new { target = "_blank" })     </td>
                             
                                        </tr>
                                        rowID = rowID + 1;
                                    }
                                </tbody>
                            </table>


                        </div>

                    </div>

                </div>


            }
        }
    }
</div>

@section scripts
{
    @*<script src="~/Scripts/DownloadPayslip.js"></script>*@

    <script>

        $(document).ready(function () {

            $('.DActive').removeClass('Active');
            $('#Payslip').addClass('Active');
            $('#Payslip2').addClass('Active');
            
        });

    </script>
    <style>
        .thcss {
            padding: 10px;
            background-color: #9b26b6;
            color: white;
            border: 1px solid #9b26b6;
            text-align: center;
        }

        .tdcss {
            padding: 10px;
            border: 1px solid #9b26b6;
            text-align: center;
        }
    </style>
}